name: Add Contributor
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add:
    if: ${{ contains(github.event.comment.body, '@all-contributors') || github.event_name == 'issues' || github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add contributor
        uses: all-contributors/all-contributors-action@v1.2.2
        if: contains(github.event.comment.body, '@all-contributors')
        with:
          args: '${{ github.event.comment.body }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        if: contains(github.event.comment.body, '@all-contributors')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "docs: add contributor" --allow-empty
          git push